language: node_js
node_js:
- "11.12.0"

before_deploy:
- rm -r ./node_modules

deploy:
  provider: s3
  cache_control: "max-age=86400"
  access_key_id: AKIAIEOS7YTGIKSU7Z7A
  secret_access_key:
    secure: bzCmpidCqO3+TlplfrJwlXqGhhXSInDHqAC2Alu4GaJgT4yhcJkRWRvYEmo/RXra4aj5zXhUQnyOJd3CMo9vxWOrUvABOHsvarfyH+q1RALqwOzYAc0FIUVcz0IocPgK1iqPVypI0CibXgltDeaQjY/kvtxBLwkqqSwzW+nxMryZa33KbXfHkwhk0FO76kZG8yLgF8N8we3VAq+CkQsIwIh4WDCzF7Ns7DzEjSr6E9STZjZ4U2jaT7A2Vq0a+JAUMIXfshfdh6cTv6sRUSJqJsJj4aQpyW1uvSAXWnfh896rs3c6w0SgRCrNhzqKLinndMkWaC2gxqzsec2mia9YD1JnK5riXDFPyNdHOcMq29BqcDzQpny2urccjTt0ruHkeASN2JhS2jhIeIeg7cMO6PYlj3MfOHQ7RarEaHtmKRRtFe2MkMuKl2BIMW1N2kOGDUtaBQdEA57vn5tHd2GQ6Uf9BAs2WSLaC1nZy6Wz8I9zqyp76RD4Ko8JXQ5P1deN98p4qccWf5rk6BOp0kStlu+Tt2h3ncCzAWROLOq8Vlb8Tj5JjW9npq+CSqzQNQ/IuxVgL3wGRHxBLqRC96dHyN/f95OpQ6trts42lCkd0xow3gPDB5rsN9KGPETzJBA9wrTmAFhqCnyGqZ0EyX9qbdqdXdbjdLXSfFTObVDTq4Q=
  bucket: psucssa-xssc
  skip_cleanup: true
  upload-dir: books/yearbook
